name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gdolfen/rr2mqtt:${{ github.event.release.tag_name }}
    - name: Docker push dockerhub
      run: |
          docker login -u gdolfen -p ${{ secrets.DOCKER_PWD }}
          docker push gdolfen/rr2mqtt:${{ github.event.release.tag_name }}
